### ISSUE TITLE
Why windows?

### ISSUE THREAD

**Issue by soyhanbeyazit** [hkutluay/UblTr#11]
Why do you use windows instead of a linux distro?

https://github.com/hkutluay/UblTr/blob/3f41bedd35ec34ce722564582d4e77a5eea19429/.github/workflows/publish.yml#L8

**Comment by hkutluay** [comment]
Hi @soyhanbeyazit ,

You can't build or deploy multi framework targeting libraries on linux distro. 

Thanks for your interest
