### ISSUE TITLE
ExtensionContent

### ISSUE THREAD

**Issue by uygaruludag** [hkutluay/UblTr#15]
Merhaba,

ubl-tr e-incoive oluşturmak istediğim de 

<ext:UBLExtensions>
		<ext:UBLExtension>
			<ext:ExtensionContent>
				<n4:auto-generated_for_wildcard/>
			</ext:ExtensionContent>
		</ext:UBLExtension>
	</ext:UBLExtensions>

xmlElementi nasıl oluşturmam gerekir ?

**Comment by hkutluay** [comment]
Merhaba,

UblTr/UblTr.Tests/InvoiceTypeTest.cs içerisinde örneğini bulabilirsiniz.
