### ISSUE TITLE
Datetime format hakkında.

### ISSUE THREAD

**Issue by mzuvin** [hkutluay/UblTr#56]
Serileştirme işlemlerinde ubltr formatına uygun olmayan serileştirme oluyor. 
```<sh:CreationDateAndTime>12.05.2022 10:17:11</sh:CreationDateAndTime>```
```<cbc:IssueTime>10:17:11.0904057+03:00</cbc:IssueTime>```

bu tarih ve saat formatını değiştirmek mümkün mü?

**Comment by hkutluay** [comment]
cbc:IssueDate format hatası için 1.1.6 versiyonunu nuget'den indirebilirsini.

sh:CreationDateAndTime bilgisi UblTr içerisinde bulunmuyor. Standard Business Document Header için kullanılan bir değer olabilir.
