### ISSUE TITLE
IssueTime Time Type stringden time a donusturuldu

### ISSUE THREAD

**Issue by Karaaslan1234** [hkutluay/UblTr#64]
Merhaba; IssueTime Alani <cbc:IssueTime>17:26:02.2560000+03:00</cbc:IssueTime> seklinde olan xml dosylarini Deserialize ederken hata aliniyor.  IssueTime Time Type stringden time a donusturuldu. ve sorun kalmadi/ bilginizi sunarim.

![image](https://user-images.githubusercontent.com/115226896/194544881-da689e41-fb20-4e79-8809-d10b15c12824.png)

**Comment by hkutluay** [comment]
Merhabalar @Karaaslan1234 ,

GIB [dokümantasyonlarında](https://ebelge.gib.gov.tr/dosyalar/kilavuzlar/UBLTR_1.2.1_Kilavuzlar.zip) `IssueTime` alanı için belirtilen kullanım şekli `Saat:Dakika:Saniye` formatında.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/1468775/194720272-3a412c2e-5e7a-4879-85ee-8e31cc41cd32.png">

Üstte belirtilen şekilde serialization datatype'ı değiştirdiğimizde bu formatta serialization yapılamıyor. Farklı bir şekilde çözüm öneriniz varsa PR açabilirsiniz.

**Comment by Karaaslan1234** [comment]
Merhaba. Gib den ubl paketlerini indirip xsd  dosyalarını .cs olarak çıkarttığınızda issutime datatype time olarak geliyor. Oysa sizin projenizde string olarak gelmekte. Paylaştığınız dokümana göre sizin düzeltme yapmanız gerekiyor. Önerimde eklediğim ekran görüntüsünü orjinal Gib dökümanından aldım. Bahsettiğim hatadaki uzun zaman formatlı kayıtları birçok entegrator firması kullanıyor. Bunlari, mevcut  dll dosyanız issuetime icin datatype string olduğundan  deserialize edemiyoruz. Bu sorunu asmak icin bulduğum yöntem Gib paketlerinden ilgili bölümü sizin projenize ekleyip yeniden derlemek oldu. Sonuç olumlu olduğu icin buradan da paylaştım. 
saygılar.
