### ISSUE TITLE
IssueTime Deserialization Hatası Hk.

### ISSUE THREAD

**Issue by saracmert** [hkutluay/UblTr#94]
Farklı firmalardan tarafımıza ulaşan bazı e-faturaları deserialize etmek istediğimde IssueTime için FormatException fırlatıyor. Bu faturalardan bazılarının IssueTime değerlerini aşağıda görebilirsiniz.

```
<cbc:IssueDate>2023-12-21</cbc:IssueDate>
<cbc:IssueTime>02:30:41.492+03:00</cbc:IssueTime>
```

```
<cbc:IssueDate>2023-12-21</cbc:IssueDate>
<cbc:IssueTime>15:21:06.0000000Z</cbc:IssueTime>
```

**Comment by hkutluay** [comment]
[v1.3.1](https://www.nuget.org/packages/UblTr/1.3.1) versiyonu ile bu hata düzeltilmiştir.
